change install dir

diff --git a/src/shade b/src/shade
--- a/src/shade
+++ b/src/shade
@@ -47,11 +47,10 @@ function setup() {
         exit 1
     fi
     success "Beginning setup"
-    rm -r /usr/local/shade/cache/ > /dev/null 2>&1
     mkdir /usr/local/shade/ > /dev/null 2>&1
-    mkdir /usr/local/shade/log/ > /dev/null 2>&1
-    mkdir /usr/local/shade/cache/ > /dev/null 2>&1
-    git clone https://github.com/shade-linux/buildscripts/ /usr/local/shade/cache/
+    mkdir /usr/local/shade/etc/log/ > /dev/null 2>&1
+    mkdir /usr/local/shade/etc/cache/ > /dev/null 2>&1
+    git clone https://github.com/shade-linux/buildscripts/ /usr/local/shade/etc/cache/
     success "Setup done!"
 }
 
@@ -66,18 +65,18 @@ function install() {
         if [[ $response =~ ^(yes|y| ) ]] || [[ -z $response ]]; then
             if command -v bat &> /dev/null
             then
-                bat -l sh --decorations never /usr/local/shade/cache/packages/${pack}/package 2>/dev/null || error "${2} buildscript not found!"
+                bat -l sh --decorations never /usr/local/shade/etc/cache/packages/${pack}/package 2>/dev/null || error "${2} buildscript not found!"
             else
-                less /usr/local/shade/cache/packages/${pack}/package || error "${2} buildscript not found!"
+                less /usr/local/shade/etc/cache/packages/${pack}/package || error "${2} buildscript not found!"
             fi
         fi
         success "Installing ${pack}"
-        find /usr/local -name "*" > /usr/local/shade/cache/packages/${pack}/pre-install
-        if ! bash /usr/local/shade/cache/packages/${pack}/package 2>/dev/null; then
+        find /usr/local -name "*" > /usr/local/shade/etc/cache/packages/${pack}/pre-install
+        if ! bash /usr/local/shade/etc/cache/packages/${pack}/package 2>/dev/null; then
             error "${pack} failed to install!"
         else
             success "${pack} installed!"
-            find /usr/local -name "*" > /usr/local/shade/cache/packages/${pack}/post-install
+            find /usr/local -name "*" > /usr/local/shade/etc/cache/packages/${pack}/post-install
         fi
     done
 }
@@ -92,14 +91,14 @@ function remove() {
         read -r -p "${bold_green}Uninstall ${pack}? [Y/n] ${normal}" response
         response=${response,,}
         if [[ $response =~ ^(yes|y| ) ]] || [[ -z $response ]]; then
-            diff /usr/local/shade/cache/packages/${pack}/pre-install /usr/local/shade/cache/packages/${pack}/post-install | tail -n +2 | cut -c 3- | xargs rm -rf
+            diff /usr/local/shade/etc/cache/packages/${pack}/pre-install /usr/local/shade/etc/cache/packages/${pack}/post-install | tail -n +2 | cut -c 3- | xargs rm -rf
             success "${pack} uninstalled!"
         fi
     done
 }
 
 function query() {
-    cat /usr/local/shade/cache/packages/*/*${2,,}*/meta 2>/dev/null || error "${2} not found!"
+    cat /usr/local/shade/etc/cache/packages/*/*${2,,}*/meta 2>/dev/null || error "${2} not found!"
 }
 
 function update() {
@@ -108,7 +107,7 @@ function update() {
         exit 1
     fi
     success "Beginning update..."
-    cd /usr/local/shade/cache/
+    cd /usr/local/shade/etc/cache/
     if ! git pull; then
         error "Update failed!"
     else
