Updated directory structure

diff --git a/src/shade b/src/shade
--- a/src/shade
+++ b/src/shade
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source /usr/local/shade/etc/config # Source config file
+
 export normal=$'\e[0m' # normal
 export bold=$(tput bold)
 
@@ -54,7 +56,7 @@ function setup() {
     mkdir /usr/local/shade/ > /dev/null 2>&1
     mkdir /usr/local/shade/etc/log/ > /dev/null 2>&1
     mkdir /usr/local/shade/etc/cache/ > /dev/null 2>&1
-    git clone https://github.com/shade-linux/buildscripts/ /usr/local/shade/etc/cache/
+    git clone https://github.com/shade-linux/buildscripts/ /usr/local/shade/etc/
     success "Setup done!"
 }
 
@@ -66,18 +68,18 @@ function install() {
         if [[ $response =~ ^(yes|y| ) ]] || [[ -z $response ]]; then
             if command -v bat &> /dev/null
             then
-                bat -l sh --decorations never /usr/local/shade/etc/cache/packages/${pack}/package 2>/dev/null || error "${2} buildscript not found!"
+                bat -l sh --decorations never /usr/local/shade/etc/packages/${pack}/package 2>/dev/null || error "${2} buildscript not found!"
             else
-                less /usr/local/shade/etc/cache/packages/${pack}/package || error "${2} buildscript not found!"
+                less /usr/local/shade/etc/packages/${pack}/package || error "${2} buildscript not found!"
             fi
         fi
-        find /usr/local -name "*" > /usr/local/shade/etc/cache/packages/${pack}/pre-install
+        find /usr/local -name "*" > /usr/local/shade/etc/packages/${pack}/pre-install
         success "Installing ${pack}"
-        if ! bash /usr/local/shade/etc/cache/packages/${pack}/package 2>/dev/null; then
+        if ! bash /usr/local/shade/etc/packages/${pack}/package 2>/dev/null; then
             error "${pack} failed to install!"
         else
-            find /usr/local -name "*" > /usr/local/shade/etc/cache/packages/${pack}/post-install
-            echo > /usr/local/shade/etc/cache/packages/${pack}/installed
+            find /usr/local -name "*" > /usr/local/shade/etc/packages/${pack}/post-install
+            echo > /usr/local/shade/etc/packages/${pack}/installed
             success "${pack} installed!"
         fi
     done
@@ -86,25 +88,25 @@ function install() {
 function remove() {
     chkroot
     for pack in ${@:2:9999}; do
-        error "WARNING: THIS FEATURE IS EXPERIMENTAL. PLEASE MAKE A BACKUP OF /usr/local/"
+        error "WARNING: THIS FEATURE IS EXPERIMENTAL. PLEASE MAKE A BACKUP OF /usr/local/shade/"
         read -r -p "${bold_green}Uninstall ${pack}? [Y/n] ${normal}" response
         response=${response,,}
         if [[ $response =~ ^(yes|y| ) ]] || [[ -z $response ]]; then
-            diff /usr/local/shade/etc/cache/packages/${pack}/pre-install /usr/local/shade/etc/cache/packages/${pack}/post-install | tail -n +2 | cut -c 3- | xargs rm -rf
-            rm /usr/local/shade/etc/cache/packages/${pack}/installed
+            diff /usr/local/shade/etc/packages/${pack}/pre-install /usr/local/shade/etc/packages/${pack}/post-install | tail -n +2 | cut -c 3- | xargs rm -rf
+            rm /usr/local/shade/etc/packages/${pack}/installed
             success "${pack} uninstalled!"
         fi
     done
 }
 
 function query() {
-    cat /usr/local/shade/etc/cache/packages/*/*${2,,}*/meta 2>/dev/null || error "${2} not found!"
+    cat /usr/local/shade/etc/packages/*/*${2,,}*/meta 2>/dev/null || error "${2} not found!"
 }
 
 function update() {
     chkroot
     success "Beginning update..."
-    cd /usr/local/shade/etc/cache/
+    cd /usr/local/shade/etc/
     if ! git pull; then
         error "Update failed!"
     else
@@ -114,12 +116,12 @@ function update() {
 
 function upgrade() {
     chkroot
-    for i in $(find /usr/local/shade/etc/cache/packages -iname 'installed' -exec dirname {} \; | sed -e 's/\/.*\///g'); do
-        cd /usr/local/shade/etc/cache/${i}
+    for i in $(find /usr/local/shade/etc/packages -iname 'installed' -exec dirname {} \; | sed -e 's/\/.*\///g'); do
+        cd /usr/local/shade/etc/${i}
         if ! git pull | grep -q 'Already up to date'; then
             cd ..
             rm -rf ${i}
-            bash /usr/local/shade/etc/cache/packages/${i}/package
+            bash /usr/local/shade/etc/packages/${i}/package
         fi
     done
 }
